config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :pillows, only: [:index, :new, :show, :create, :update, :edit, :destroy]


  resources :bookings, only: [:index, :show, :update, :edit, :destroy] do
    resources :reviews, only: [:new, :create, :destroy]
  end


  resources :pillows do
    resources :bookings, only: [:new, :create]
  end


  # delete "bookings/:id", to: "bookings#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :start_date, :end_date, presence: true

  belongs_to :user
  belongs_to :pillow
  has_one :review
end

app/models/pillow.rb
class Pillow < ApplicationRecord
  mount_uploader :photo, PhotoUploader

  validates :category, :address, presence: true

  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :content, :rating, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:full_name])
    # # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :authenticate_user!, only: :new
  before_action :find_booking, only: [:destroy]

  def index
    @bookings = Booking.where(user: current_user)
    @user = current_user
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @pillow = Pillow.find(params[:pillow_id])
    @booking = Booking.new
  end

  def create
    user = current_user
    pillow = Pillow.find(params[:pillow_id])
    @booking = Booking.new(booking_params)
    @booking.user = user
    @booking.pillow = pillow
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def destroy
    # raise
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def find_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/pillows_controller.rb
class PillowsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :find_pillow, only: [:edit, :update, :destroy]

  def index
    @pillows = Pillow.all
  end

  def show
    @pillow = Pillow.find(params[:id])
    @reviews = Review.where(params[:pillow_id])
  end

  def new
    @pillow = Pillow.new
  end

  def create
    @pillow = Pillow.new(pillow_params)
    if @pillow.save
      redirect_to pillows_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @pillow.update(pillow_params)
    redirect_to pillows_path(@pillow)
  end

  def destroy
    @pillow.destroy
    redirect_to pillows_path
  end

  private

  def find_pillow
    @pillow = Pillow.find(params[:id])
  end

  def pillow_params
    params.require(:pillow).permit(:address, :category, :name, :photo, :description)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save
      redirect_to pillow_path(@booking.pillow)
    else
      render 'reviews/new'
    end
  end

  def destroy
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating, :booking_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container"><h1>Overview of your Bookings</h1>

  <p>Bookings made with: <%= @user.email%></p>

  <% if @bookings.empty? %>
    <p> Sorry no Bookings yet 😥</p>
    <p> <%= link_to "Browse our Pillows 🤪", pillows_path %></p>
  <% else %>
      <% @bookings.each do |booking| %>
        <div class="booking-container">
          <div class="card-booking-product">
            <%= cl_image_tag(booking.pillow.photo,
                  width: 300, height: 300, crop: :fill) %>
            <div class="card-booking-info">
              <h3> <%= booking.pillow.name %> </h3>
              <p> from: <%= booking.start_date %>  </p>
              <p> to: <%= booking.end_date %> </p>
              <p>Price per night € <%= booking.pillow.price %></p>
            </div>
          </div>
          <div class="d-flex px-3 my-5 justify-content-around">
            <div class="button-detail">
              <%= link_to "Detail pillow", pillow_path(booking.pillow.id) %>
            </div>
            <div class="button-detail">
              <%= link_to "Details booking", booking_path(booking) %>
            </div>
            <div class="button-detail">
              <%= link_to "Delete", booking_path(booking),
                method: :delete,
                data: { confirm: "Are you sure?" } %>
            </div>
          </div>
        </div>
      <% end %>
  <% end %>
</div>

app/views/bookings/new.html.erb
<h1 class='title-form'>This is the booking page for the pillows!</h1>
<div class="form-container">
   <%= simple_form_for([@pillow, @booking]) do |f| %>
    <%= f.error_notification %>
    <div class=“form-inputs”>
      <div class="container-flex-inline">
      <h4>For pillow: </h4> <p> <%= @pillow.name %></p>
      </div>
      <h4>Address: </h4> <p> <%= @pillow.address %> </p>
      <%= f.input :start_date %>
      <%= f.input :end_date %>
    </div>
    <div class=“form-actions”>
      <%= f.button :submit, class: 'button-detail' %>
    </div>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="wrapper-margin-top wrapper-w800 wrapper-margin-top">
  <h1>You're booking is confirm!</h1>
  <p>Congratulation, you're booking for the pillow <strong>"<%= @booking.pillow.name %>"</strong> is confirmed!</p>


  <div class="info-booking-container">
    <div class="d-flex flex-column">
      <h2> <%= @booking.pillow.name %> </h2>
      <p>Booking number: <%= @booking.id %> </p>
      <h5>Description</h5>
      <p>
        <%= @booking.pillow.description %>
      </p>
      <h5>Category</h5>
      <p> <%= @booking.pillow.category %></>
    </div>
    <div class="date-booking-container">
      <h5>Dates</h5>
      <div class="start-date">
        <p>start date: </p> <%= @booking.start_date %> <br>
      </div>
      <div class="end-date">
        <p>end date: </p> <%= @booking.end_date %> <br>
      </div>
    </div>
  </div>

  <div class="d-flex px-3 justify-content-around">
    <div class="button-detail">
      <%= link_to 'See all your bookings', bookings_path  %>
    </div>
    <div class="button-detail">
      <%= link_to 'Add review', new_booking_review_path(@booking)  %>
  </div>
</div>
  </div>


   <div class="center">
    <svg x="0px" y="0px" viewBox="0 0 128 128" stroke="#000" stroke-width="3" stroke-linecap="round" stroke-linejoin="round">
        <path id="body">
            <animate attributeName="fill" dur="500ms" repeatCount="indefinite" keyTimes="0;0.1;0.2;0.3;0.4;0.5;0.6;0.7;0.8;0.9;1" values="
                #ff8d8b;
                #fed689;
                #88ff89;
                #87ffff;
                #8bb5fe;
                #d78cff;
                #ff8cff;
                #ff68f7;
                #fe6cb7;
                #ff6968;
                #ff8d8b
            "/>
            <animate attributeName="d" dur="500ms" repeatCount="indefinite" keyTimes="0;0.1;0.2;0.3;0.4;0.5;0.6;0.7;0.8;0.9;1" values="
                M67.1,109.5c-9.6,0-23.6-8.8-23.6-24c0-12.1,17.8-41,37.5-41c15.6,0,23.3,10.6,25.1,20.5 c1.9,10.7,3.9,8.2,3.9,19.5c0,8.2-3.8,17-3.8,22.3c0,3.9,1.4,7.4,2.9,10.5c1.7,3.5,2.4,6.6,2.4,9.2H9.5c0-13.7,10.8-14,21.1-23 c5.6-4.9,11-12.4,14.5-26;
                M56.1,107.5c-9.6,0-24.6-13.8-24.6-29c0-16.2,13-42,33.5-42c17.8,0,22.3,11.6,26.1,22.5 c3.6,10.3,9.9,9.2,9.9,20.5c0,8.2-1.8,7-1.8,12.3c0,4.5,3.4,8.2,6.4,14.1c2.5,4.8,4.8,11.2,4.8,20.6h-99c0-12.1,7.2-17.6,14.7-24.3 c3.2-2.9,6.5-5.9,9.2-9.8;
                M45.1,109.5c-5.5-0.2-27.6-8.4-27.6-27c0-17.9,14.8-42,32.5-42c15.4,0,24,10.4,26.1,21.5 c1.3,6.7,9.9,9.8,9.9,21.5c0,8.2-0.8,6-0.8,11.3c0,7.7,12.8,9,20.8,15c7.7,5.8,15.5,16.7,15.5,16.7h-110c0-4.8,1.7-11.3,5-16 c3.2-4.5,4.5-8.3,5-15;
                M36,120c-5.5-0.2-28.5-11.9-28.5-30.5c0-16.2,12.5-42,33-42c17.8,0,21.8,9.6,25.6,20.5 C69.7,78.3,76,78.2,76,89.5c0,8.2-0.8,4-0.8,9.3c0,5.9,16.5,7.8,28.4,15.9c8,5.5,17.9,11.8,17.9,11.8h-110c0-2.1-1.2-5.2-1.9-14.5 c-0.3-3.6-0.5-8.1-0.5-13.9;
                M37,119.5c-15,0.1-33.5-12.7-33.5-30C3.5,73.3,16,47,36.5,47c17.8,0,22.8,11,26,22 C65.6,79.4,73,79.2,73,90.5c0,4-1.8,6.6-1.8,8.3c0,5.9,14.2,6.4,26.4,15.9c7.7,6,13.9,11.8,13.9,11.8H7.5c-1.2-3.4-1.8-7.3-1.9-11.2 c-0.2-5.1,0.3-10.1,0.9-13.7;
                M40.5,121.5c-12.6,0-30-13.4-30-29C10.5,76.3,23,53,43.5,53c14.5,0,22.8,9.6,25,22 c1.2,6.9,10,9.2,10,20.5c0,4,0,5.6,0,7.3c0,4.9,6.1,7.5,11.2,11.9c5.8,5,7.2,11.8,7.2,11.8H8.5c0-1.5-0.6-6.1,0.4-11.8 c0.6-3.5,1.9-7.5,4.3-11.6;
                M48.5,121.5c-12.6,0-25-6.3-25-18c0-16.2,13.7-47,36-47c15.6,0,24.8,9.1,27,21.5 c1.2,6.9,7,9.2,7,18.5c0,9.5-4,11-4,22c0,4.1,0.5,5,1,6c0.5,1.2,1,2,1,2h-81c0-5.3,3.1-8.3,6.3-11.5c2.6-2.6,5.4-5.3,6.7-9.5;
                M68.5,121.5c-12.6,0-33-5.8-33-23c0-9.2,11.8-36,37-36c15.6,0,25.8,8.1,28,20.5 c1.2,6.9,4,6.2,4,15.5c0,9.5-5,15.1-5,21c0,1.9,1,2.3,1,5c0,1.2,0,2,0,2h-91c0.5-7.6,7.1-11.1,13.7-15.7c4.9-3.4,9.9-7.5,12.3-14.3;
                M73.5,117.5c-12.6,0-30-6.2-30-25c0-14.2,20.9-37,38-37c17.6,0,25.8,11.1,28,23.5 c1.2,6.9,3,7.2,3,16.5c0,12.1-6,16.1-6,22c0,4.2,2,5.3,2,8c0,1.2,0,1,0,1H7.5c2.1-9.4,10.4-13.3,19.2-19.4 c7.1-5,14.4-11.5,18.8-23.6;
                M80.5,115.5c-12.6,0-32-9.2-32-28c0-14.2,22.9-35,40-35c17.6,0,25.8,12.1,28,24.5 c1.2,6.9,3,6.2,3,15.5c0,12.1-6,19.1-6,25c0,4.2,2,5.3,2,8c0,1.2,0,1,0,1h-102c2.3-8.7,11.6-11.7,20.8-20.1 c5.3-4.8,10.5-11.4,14.2-21.9;
                M67.1,109.5c-9.6,0-23.6-8.8-23.6-24c0-12.1,17.8-41,37.5-41c15.6,0,23.3,10.6,25.1,20.5 c1.9,10.7,3.9,8.2,3.9,19.5c0,8.2-3.8,17-3.8,22.3c0,3.9,1.4,7.4,2.9,10.5c1.7,3.5,2.4,6.6,2.4,9.2H9.5c0-13.7,10.8-14,21.1-23 c5.6-4.9,11-12.4,14.5-26
            "/>
        </path>
        <path id="beak" fill="#7b8c68">
            <animate attributeName="d" dur="500ms" repeatCount="indefinite" keyTimes="0;0.1;0.2;0.3;0.4;0.5;0.6;0.7;0.8;0.9;1" values="
                M78.29,70c0-9.92,2.5-14,8-14s8,2.17,8,10.67c0,15.92-7,26.33-7,26.33S78.29,85.5,78.29,70Z;
                M62.29,64c0-9.92,2.5-14,8-14s8,2.17,8,10.67c0,15.92-7,26.33-7,26.33S62.29,79.5,62.29,64Z;
                M48.29,67c0-9.92,2.5-14,8-14s8,2.17,8,10.67c0,15.92-7,26.33-7,26.33S48.29,82.5,48.29,67Z;
                M36.29,73c0-9.92,2.5-14,8-14s8,2.17,8,10.67c0,15.92-7,26.33-7,26.33S36.29,88.5,36.29,73Z;
                M35.29,75c0-9.92,2.5-14,8-14s8,2.17,8,10.67c0,15.92-7,26.33-7,26.33S35.29,90.5,35.29,75Z;
                M41.29,81c0-9.92,2.5-14,8-14s8,2.17,8,10.67c0,15.92-7,26.33-7,26.33S41.29,96.5,41.29,81Z;
                M59.29,84c0-9.92,2.5-14,8-14s8,2.17,8,10.67c0,15.92-7,26.33-7,26.33S59.29,99.5,59.29,84Z;
                M72.29,89c0-9.92,2.5-14,8-14s8,2.17,8,10.67c0,15.92-7,26.33-7,26.33S72.29,104.5,72.29,89Z;
                M80.29,82c0-9.92,2.5-14,8-14s8,2.17,8,10.67c0,15.92-7,26.33-7,26.33S80.29,97.5,80.29,82Z;
                M87.29,78c0-9.92,2.5-14,8-14s8,2.17,8,10.67c0,15.92-7,26.33-7,26.33S87.29,93.5,87.29,78Z;
                M78.29,70c0-9.92,2.5-14,8-14s8,2.17,8,10.67c0,15.92-7,26.33-7,26.33S78.29,85.5,78.29,70Z
            "/>
        </path>
        <ellipse id="eye-right" rx="3" ry="4">
            <animate attributeName="cx" dur="500ms" repeatCount="indefinite" keyTimes="0;0.1;0.2;0.3;0.4;0.5;0.6;0.7;0.8;0.9;1" values="100;84;70;58;57;63;81;94;102;109;100"/>
            <animate attributeName="cy" dur="500ms" repeatCount="indefinite" keyTimes="0;0.1;0.2;0.3;0.4;0.5;0.6;0.7;0.8;0.9;1" values="62;56;59;65;67;73;76;81;74;70;62"/>
        </ellipse>
        <ellipse id="eye-left" rx="3" ry="4">
            <animate attributeName="cx" dur="500ms" repeatCount="indefinite" keyTimes="0;0.1;0.2;0.3;0.4;0.5;0.6;0.7;0.8;0.9;1" values="67.5;51.5;37.5;25.5;24.5;30.5;48.5;61.5;69.5;76.5;67.5"/>
            <animate attributeName="cy" dur="500ms" repeatCount="indefinite" keyTimes="0;0.1;0.2;0.3;0.4;0.5;0.6;0.7;0.8;0.9;1" values="62;56;59;65;67;73;76;81;74;70;62"/>
        </ellipse>
    </svg>
    <input type="range" min="200" max="2000" value="500" step="1" id="animationDuration" onchange="updateDuration(this.value)" oninput="updateDuration(this.value)">
</div>

<p style='font-size:200px; text-align:center;'>Oh yeah!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Pillow Talk!</title>
    <%= favicon_link_tag 'party_parrot.jpg' %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <nav class='navbar-wrapper'>
    <%= render 'shared/navbar' %>
    </nav>
    <div class="wrapper">
    <%= yield %>
    </div>
    <%= render 'shared/flashes' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-on-banner"><h1>You can't own all Pillows</h1>
    <h2>But you can rent them!</h2>
    <p class="button-banner"><%= link_to 'GET EM ALL', pillows_path %></p>
  </div>
</div>

<!-- <img src="https://img.icons8.com/ios/50/000000/pillow.png">
 -->

<div class="subtext">
  <h3 id="h3-style">
    <strong>A wise weirdo once said...</strong>
  </h3>
  <br>
  <h3 id="h3-style"> Softly cushion
     my weary head
     with feathered delight
     that will propel
     me into the pastel
     backdrop of sugary dreams
     <br>
     - I love you little pillow
     <img src="https://img.icons8.com/ios/50/000000/pillow.png">
  </h3>
</div>

<div class="gif">
    <iframe src="https://giphy.com/embed/d2jsIygHeoPqvOgg" width="1000" height="900" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
</div>

<h3 id="h3-style"> In case you want to rent some other cool shit:
  </h3>

<div class="footer-home">
  <ul id="ul-home">
    <li>
      <%= link_to 'https://power-up-granttnarg.herokuapp.com/', target: :_blank do %>
      <img src="https://img.icons8.com/wired/64/000000/superman.png">
      <% end %>
    </li>
    <li>
      <%= link_to 'https://can-i-dig-it.herokuapp.com/', target: :_blank do %>
      <img src="https://img.icons8.com/wired/64/000000/road-worker.png">
      <% end %>
    </li>
    <li>
      <%= link_to 'http://meowtimes-288.herokuapp.com/', target: :_blank do %>
       <img src="https://img.icons8.com/wired/64/000000/cat-butt.png">
      <% end %>
    </li>
    <li>
      <%= link_to 'https://alpacando.herokuapp.com/', target: :_blank do %>
      <img src="https://img.icons8.com/wired/64/000000/alpaca.png">
      <% end %>
    </li>
  </ul>
</div>

app/views/pillows/edit.html.erb
<div class="wrapper">
  <div class="form-container">
    <h1>Edit this pillow</h1>
    <%= simple_form_for(@pillow) do |f| %>
      <%= f.error_notification %>
     <div class=“form-inputs”>
       <%= f.input :name %>
       <%= f.input :description %>
       <%= f.input :address %>
       <%= f.input :category %>
       <%= f.input :photo %>
       <%= f.input :photo_cache, as: :hidden %>

     </div>
     <div class=“form-actions”>
       <%= f.button :submit, class: 'button-detail' %>
     </div>
    <% end %>
  </div>
</div>

app/views/pillows/index.html.erb
<div class="wrapper wrapper-margin-top" id="center-top">
  <p class="funky-pic">.</p>
    <h1>Dicover our terrific pillows</h1>
    <p>
      And please don't get distracted by our awesome 90's design
    </p>
  <p class="funky-pic">.</p>
</div>


<div class="pillow-container-grid">
  <div class="row p-2 mb-3 justify-content-between">
    <% @pillows.each do |pillow| %>
    <%= render 'shared/card', pillow: pillow %>
    <% end %>
  </div>
</div>

app/views/pillows/new.html.erb
<div class="wrapper">
  <div class="form-container">
    <h1>Add a pillow</h1>
    <%= simple_form_for(@pillow) do |f| %>
      <%= f.error_notification %>
     <div class=“form-inputs”>
       <%= f.input :name %>
       <%= f.input :description %>
       <%= f.input :address %>
       <%= f.input :price %>
       <%= f.input :category %>
       <%= f.input :photo %>
       <%= f.input :photo_cache, as: :hidden %>

     </div>
     <div class=“form-actions”>
       <%= f.button :submit, class: 'button-detail' %>
     </div>
    <% end %>
  </div>
</div>

app/views/pillows/show.html.erb
<div class="wrapper-index wrapper-margin-top container">
  <div class="pillow-container-grid card-pillow-show">
    <div class="row d-flex p-2 mb-3 justify-content-between">

      <%= cl_image_tag(@pillow.photo,
               crop: :fill) %>

      <div class="container-flex-inline">
        <h1 id="h1"><%= @pillow.name %></h1>
        <h4><strong>Description:</strong></h4>
        <p class="sub-sub-text"> <%= @pillow.description %></p>

        <h4><strong>Category:</strong></h4>
        <p class="sub-sub-text"> <%= @pillow.category %></p>


        <h4><strong>Address:</strong></h4>
        <p class="sub-sub-text"> <%= link_to @pillow.address, "https://www.google.de/maps/search/#{@pillow.address}", target: :blank %> </p>

        <h4><strong>rating:</strong></h4>
        <p class="sub-sub-text"> 5 stars</p>

        <h4><strong>price</strong></h4>
        <p class="sub-sub-text"> <%= @pillow.price %>€</p>

      </div>
    </div>

          <div class="d-flex px-3 justify-content-around">
            <%# if current_user == @pillow.id%>
            <div class="button-detail">
              <%= link_to "Edit", edit_pillow_path(@pillow) %>
            </div>
            <div class="button-detail">
              <%= link_to "Remove", pillow_path(@pillow), method: :delete  %>
            </div>
            <%# end %>
            <div class="button-detail">
              <%= link_to "Book this pillow!", new_pillow_booking_path(@pillow) %>
            </div>
          </div>

  </div>

   <div style='margin-top: 50px;'>
    <h4>Reviews</h4>
        <% @reviews.each do |t| %>
          <div class="card-product-infos">
            <h5><%= t.booking.user.full_name %></h5>
            <p><%= t.content %></p>
            <% counter = 0 %>
            <% 5.times do %>
              <i class="fa <%= t.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
               <% counter += 1 %>
            <% end %>
          </div>
        <% end %>
  </div>
</div>

app/views/reviews/_new.html.erb
<h3>Add a review</h3>
<%= simple_form_for [cocktail, review] do |f| %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.input :content %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/reviews/new.html.erb
<h1 style='text-align:center;'> Add a review</h1>
<div class="form-container">
  <%= simple_form_for [@booking, @review] do |f| %>
    <%= f.input :rating, collection: 0..5 %>
    <%= f.input :content %>
    <%= f.submit class: "button-detail"%>
  <% end %>
</div>

app/views/shared/_card.html.erb
<%= link_to pillow_path(pillow.id), :action => 'go', class: "a-in-card" do %>
<!--   <div class='card-pillow mb-3'>

    <div class="pillow-card-content">
        <#%= cl_image_tag pillow.photo, alt: "alttext" %>
      <div class="pillow-card-info">
        <h2 class='pillow-name'> <%#= pillow.name %> </h2>
        <h3 class='pillow-category'> <%= pillow.category %></h3>
        <p class='pillow-description'> <%= pillow.description %> </p>
      </div>
    </div>
  </div> -->
<div class='card-pillow'>
  <div class='pillow-card-image' style='background-image: url(<%= pillow.photo %>)'>

  </div>
  <div class="pillow-card-content">
    <h3> <%= pillow.category %> </h3>
    <h2> <%= pillow.name %> </h2>
    <p> <%= pillow.description %> </p>
    <p> <%= pillow.price %> €</p>
    <% 5.times do %>
    <i class="fas fa-star"></i>
    <% end %>
  </div>
</div>

<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "Logo-new.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown"> Home
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Bookings", bookings_path, class: "dropdown-item" %>
            <%= link_to "Add a pillow for rent", new_pillow_path, class: "dropdown-item" %>
            <%= link_to "Magic Website", 'https://cultofthepartyparrot.com', class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
           <%= image_tag "party_parrot_real", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>